---
abstract: 'Get a Data::Pageset pager from a resultset'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-ResultSet-Data-Pageset
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  Data::Pageset: 1.02
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bricas/dbix-class-resultset-data-pageset/tree/master
version: 0.06
