--- 
abstract: Get a Data::Pageset pager from a resultset
author: Brian Cassidy
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-ResultSet-Data-Pageset
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0
  Data::Pageset: 0
  Test::More: 0
version: 0.01
